-- Create the table for hero carousel slides
CREATE TABLE public.hero_carousel_slides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  title TEXT NOT NULL,
  subtitle TEXT,
  image_path TEXT NOT NULL, -- Path to the image in the 'hero-banners' storage bucket
  cta_link TEXT,
  cta_text TEXT,
  display_order INT DEFAULT 0 NOT NULL,
  is_active BOOLEAN DEFAULT true NOT NULL
);

-- Enable Row Level Security (RLS) for the table
ALTER TABLE public.hero_carousel_slides ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow public read access to active slides
CREATE POLICY "Allow public read access to active slides"
ON public.hero_carousel_slides
FOR SELECT
USING (is_active = true);

-- Add comments for clarity
COMMENT ON COLUMN public.hero_carousel_slides.image_path IS 'Path to the image in the ''hero-banners'' storage bucket.';
COMMENT ON POLICY "Allow public read access to active slides" ON public.hero_carousel_slides IS 'Anyone can read active slides.';
